export const REQUEST = "REQUEST";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const FETCH_BY_ID = "FETCH_BY_ID";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY_BY_ID = "DELETE_CATEGORY_BY_ID";
export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";
export const GET_ALL_PRODUCT_SUBCATEGORY_CATEGORY =
  "GET_ALL_PRODUCT_SUBCATEGORY_CATEGORY";
export const GET_ALL_PRODUCT_BY_PRICE = "GET_ALL_PRODUCT_BY_PRICE";
export const ERROR = "ERROR";
