export const sizeOptions = [
  { label: "small", value: "small" },
  { label: "medium", value: "medium" },
  { label: "large", value: "large" },
  { label: "x-large", value: "x-large" },
  { label: "xx-large", value: "xx-large" },
  { label: "xxx-large", value: "xxx-large" },
  { label: "xxxx-large", value: "xxxx-large" },
];

export const colorOptions = [
  { label: "Red", value: "Red" },
  { label: "CadetBlue", value: "CadetBlue" },
  { label: "Eagle", value: "Eagle" },
  { label: "Gold", value: "Gold" },
  { label: "LightSlateGrey", value: "LightSlateGrey" },
  { label: "RoyalBlue", value: "RoyalBlue" },
  { label: "Crimson", value: "Crimson" },
  { label: "Blue", value: "Blue" },
  { label: "Sienna", value: "Sienna" },
  { label: "Indigo", value: "Indigo" },
  { label: "Green", value: "Green" },
  { label: "Violet", value: "Violet" },
  { label: "GoldenRod", value: "GoldenRod" },
  { label: "OrangedRed", value: "OrangedRed" },
  { label: "Khaki", value: "Khaki" },
  { label: "Teal", value: "Teal" },
  { label: "Purple", value: "Purple" },
  { label: "Orange", value: "Orange" },
  { label: "Pink", value: "Pink" },
  { label: "Black", value: "Black" },
  { label: "DarkTurquoise", value: "DarkTurquoise" },
];

export const tags = [
  "Title",
  "Vendor",
  "Image",
  "Category",
  "SubCategory",
  "Brand",
  "Rates",
  "Description",
  "Price",
  "Size",
  "Color",
  "Quantity",
  "Status",
  "Actions",
];
